modify github action

diff --git a/.github/workflows/pre-release.yml b/.github/workflows/pre-release.yml
--- a/.github/workflows/pre-release.yml
+++ b/.github/workflows/pre-release.yml
@@ -110,7 +110,12 @@ jobs:
       - name: Exit
         id: exit
         run: |
-          if [ "${{ steps.check.outputs.release_name_check }}" == "false" ]; then
+          need_release="${{ steps.check-release-name.outputs.need_release }}"
+          checked="${{ steps.check.outputs.release_name_check }}"
+          if [ $need_release == "false" ]; then
+            echo "::error::Release name check failed."
+            exit 1
+          elif [ $checked == "false"]; then
             echo "::error::Release name check failed."
             exit 1
           else
